# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85e1866424393bc2e2a28564a68d68b35d206f1bec242fb901ab3e1cc13c23d7e5d0e345a8f114695aa4a77e8ecb7cdca1092a690222814b04eed6b434627949

test:
  secret_key_base: 6ec8b7fe97fb6a115dae62d103f5a7faddb4566fd725acbc350b44da2b6d056c5acdcb51d6ddf8a83467d5b70b6ba145fc765a9e3c0bd90cf39c88ac0afd45f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
